trigger:
  branches:
    include:
      - main

variables:
  # Nombre que tendrá la imagen dentro del registro
  IMAGE_NAME: 'mysql-devops'


jobs:
  - job: BuildAndPush
    displayName: 'Compilar y Empujar Imagen MySQL a ACR'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Docker@2
        displayName: 'Build and Push Docker Image ACR'
        inputs:
          command: 'buildAndPush'
          containerRegistry: '$(SERVICE_CONNECTION_NAME)'
          repository: '$(ACR_NAME).azurecr.io/(IMAGE_NAME)'
          dockerfile: '**/Dockerfile'
          tags: |
            latest
            $(Build.BuildId)
